services:
  db:
    image: postgres:15
    container_name: ims_db_prod
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ims_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

  app:
    image: ${DOCKER_USERNAME}/ims-app:latest
    container_name: ims_app_prod
    restart: always
    ports:
      - "80:3000" # Mapping port 80 of EC2 to 3000 of container
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/ims_db?schema=public
      PORT: 3000
      NODE_ENV: production
    depends_on:
      - db

volumes:
  pgdata_prod:
