
services:
  db:
    image: postgres:15
    container_name: ims_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ims_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: ims_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/ims_db?schema=public
      PORT: 3000
      NODE_ENV: development
    depends_on:
      - db
    volumes:
      # Use long syntax to prevent Docker from getting confused by the colon (:) in your folder name "CI:CD"
      - type: bind
        source: .
        target: /usr/src/app
      - /usr/src/app/node_modules
      # Ignore generated Prisma files from host to prevent conflicts
      - /usr/src/app/node_modules/.prisma

volumes:
  pgdata:
